/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.api.gateway;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testFindFirstRepeatedWord() {
        Library library = new Library();

    }
}
