/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.api.gateway;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;

public class Library {
    public String findFirstRepeatedWord(String sentence) {
        String[] words = sentence.split(" ");
        Hashtable occurrences = new Hashtable();

        for (String word: words) {
            word = word.replaceAll("\\p{Punct}", "");
            if (occurrences.containsKey(word)) {
                return word;
            } else {
                occurrences.put(word, 1);
            }
        }
        return "no repeated words";
    }
}
