/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.api.gateway;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;

public class Library {
    public String findFirstRepeatedWord(String sentence, Context c) {
        LambdaLogger logger = c.getLogger();
        logger.log(sentence);
        return "";
    }
}
